config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  authenticate :user, -> (u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics"
  end

  root to: 'pages#home'
  resources :users, param: :slug do
    resources :mirrors, only: [:update]
    get '/ongoing_projects', to: 'mirrors#ongoing_projects'
    get '/portfolio', to: 'mirrors#past_projects'
  end
  get '/confirmation_pending', to: 'users#after_registration_path'
  resources :projects, param: :slug do
    resources :collabs, only: [:new, :create]
    resources :jobs, only: [:new, :create]
  end
  resources :collabs, only: [:destroy]

  resources :jobs, only: [:show, :destroy, :edit, :update, :index] do
    resources :inquiries, only: [:new, :create]
  end
  resources :inquiries, only: [:show, :destroy, :edit, :update] do
    member do
      patch :change_status
    end
  end
  resources :chatrooms, only: [:show, :index]
  resources :messages, only: [:create]
  resources :events, param: :slug, only: [:show, :index] do
    member do
      post :attend
      post :unattend
    end
  end


  get '/dashboard', to: 'dashboards#dashboard'
  get '/upcoming_projects_dash', to: 'dashboards#upcoming_projects_dash'
  get '/past_projects_dash', to: 'dashboards#past_projects_dash'
  get '/open_jobs_dash', to: 'dashboards#open_jobs_dash'
  get '/close_jobs_dash', to: 'dashboards#close_jobs_dash'
  get '/hold_received_dash', to: 'dashboards#hold_received_dash'
  get '/accepted_received_dash', to: 'dashboards#accepted_received_dash'
  get '/rejected_received_dash', to: 'dashboards#rejected_received_dash'
  get '/upcoming_collabs_dash', to: 'dashboards#upcoming_collabs_dash'
  get '/past_collabs_dash', to: 'dashboards#past_collabs_dash'
  get '/hold_sent_dash', to: 'dashboards#hold_sent_dash'
  get '/accepted_sent_dash', to: 'dashboards#accepted_sent_dash'
  get '/rejected_sent_dash', to: 'dashboards#rejected_sent_dash'

  get '/upcoming_projects', to: 'projects#upcoming_projects'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :project
  has_many :inquiries, dependent: :destroy
  validates :title, presence: true,
                    format: { without: /(<|>|&)/, message: "cannot include special characters" },
                    length: { maximum: 100, message: "is too long" }
  validates :description, presence: true, format: { without: /(<|>|&)/, message: "cannot include <, >, and &" }
  validates :money, presence: true, numericality: { greater_than_or_equal_to: 0, message: "value must be positive" }

  enum payment: { fixed_rate: "fixed_rate", hourly_rate: "hourly_rate" }
  enum status: { open: "open", close: "close" }

  include PgSearch::Model

  pg_search_scope :search_by_title_description_skills, against: {
    title: "A",
    skills_needed: "A",
    description: "B"
  }, using: {
    tsearch: { prefix: true, any_word: true }
  }

  def applied?(current_user)
    applicants = inquiries.map(&:user)
    applicants.include? current_user
  end

  def display_skills
    Services::TagsRenderer.new(skills_needed).format_tags
  end

  def self.filter_jobs_on(payment_type)
    Job.where(payment: payment_type)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: %i[show edit update destroy]
  before_action :find_project, only: %i[new create]

  def index
    @jobs = policy_scope(Job)
    if params[:search].present? && params[:search][:payment] != "all"
      @jobs = Job.filter_jobs_on(params[:search][:payment])
    end
    @autocomplete_set = Services::AutocompleteGenerator.new.skill_set
    @jobs = @jobs.search_by_title_description_skills(params[:query]) if params[:query].present?
    respond_to do |format|
      format.html
      format.text { render partial: 'index_job.html.erb', locals: { jobs: @jobs, query: params[:query] } }
    end
  end

  def show
    @message = Message.new
  end

  def new
    @job = Job.new
    authorize @job
    @location_autocomplete_set = Services::AutocompleteGenerator.new.location_set
  end

  def create
    @job = Job.new(job_params)
    authorize @job
    @job.project = @project
    if @job.save
      redirect_to dashboard_path, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @job.update(job_params)
    if @job.save
      redirect_to dashboard_path, notice: 'Job was successfully updated.'
    else
      render :new
    end
  end

  def destroy
    @job.destroy
    redirect_to dashboard_path, notice: 'Job was successfully deleted.'
  end

  private

  def find_job
    @job = Job.find(params[:id])
    authorize @job
  end

  def find_project
    @project = Project.find_by(slug: params[:project_slug])
  end

  def job_params
    params.require(:job).permit(:title, :description, :location, :money, :payment, :status, :skills_needed)
  end
end

app/views/jobs/_form.html.erb
<%= simple_form_for [ @project, @job ], remote: true, html: { class: "form-js"} do |f| %>
  <%= f.input :title, label: 'Job title:', required: true, wrapper_html: { class: "form-page__job-title" }, label_html: { class: 'form-page__label' }, input_html: { autocomplete: "off", class: "form-page__input form-page__input--job-title" } %>
  <%= f.input :description, label: 'Describe the job:', required: true, wrapper_html: { class: "form-page__job-description" }, label_html: { class: 'form-page__label' }, input_html: { class: "form-page__input form-page__input--big" } %>
  <%= f.input :location, label: 'Job location:', wrapper_html: { data: { set: @location_autocomplete_set.to_json }, class: "form-page__job-location search-data-js" }, label_html: { class: 'form-page__label' }, input_html: { class: 'form-page__input search-input-js' } %>
  <%= f.input :skills_needed, wrapper_html: { class: "form-page__skills-hidden-field" }, input_html: { class: "attributes_hidden_field_js" } %>
  <div class="form-page__skills-custom">
    <div class="form-page__add-skills">
      <label for="fname" class="form-page__add-skills-label form-page__label">New skill:</label>
      <div class="form-page__add-skills-input-and-btn">
        <input type="text" id="fname" class="form-page__add-skills-input form-page__input attribute-value-js"></input>
        <div class="form-page__add-skills-btn btn-add-attribute-js">Add</div>
      </div>
    </div>
    <div>
      <label class="form-page__skills-list-label form-page__label">Skills list:</label>
      <ol class="form-page__skills-list-items attributes-list-js"></ol>
    </div>
  </div>
  <div class="form-page__job-payment-and-status">
    <div class="form-page__payment-type-dropdown-wrapper">
      <%= f.input :payment, label: 'Payment type:', as: :select, collection: [["fixed rate", "fixed_rate"], ["hourly rate", "hourly_rate"]], include_blank: false, wrapper_html: { class: "form-page__payment-type-dropdown" }, input_html: { class: "form-page__input form-page__payment-type-input dropdown-payment-js" }, label_html: { class: "form-page__label form-page__payment-type-label" } %>
      <i class="fas fa-angle-down"></i>
    </div>
    <div class="form-page__job-money-wrapper">
      <%= f.input :money, label: 'Money:', required: true, wrapper_html: { class: "form-page__job-money" }, label_html: { class: "form-page__label form-page__job-money-label" }, input_html: { class: "form-page__input form-page__job-money-input", value: "100", step: "10", min: "0" } %>
      <div class="form-page__job-money-trailing-label job-payment-js">€ total</div>
    </div>
    <div class="form-page__job-status-wrapper">
      <%= f.input :status, label: 'Status:', as: :select, collection: ["open", "close"], include_blank: false, wrapper_html: { class: "form-page__job-status" }, input_html: { class: "form-page__input form-page__job-status-input" }, label_html: { class: "form-page__label form-page__job-status-label" } %>
      <i class="fas fa-angle-down"></i>
    </div>
  </div>
  <%= f.submit "Save!", class: "form-page__submit-btn form-btn-js" %>
  <button class="form-page__loading-btn form-page__loading-btn--hidden form-btn-js" type="button" disabled>
    <span class="spinner-border" role="status" aria-hidden="true"></span>
    Loading...
  </button>
<% end %>

app/views/jobs/_index_job.html.erb
<div class="search-results-js">
  <% if query.blank? %>
    <h4 class="placeholder-numbers-results"></h4>
  <% else %>
    <h4 class="numbers-results"><%= jobs.count %> <%= "jobs".pluralize(jobs.count) %> matched your search for "<%= query %>"</h4>
  <% end %>
  <div class="job-results-grid">
    <% jobs.each do |job| %>
      <div class="job-card__wrapper highlight-js">
        <div class="job-card__title">
          <h2 class="job-card__title-text highlight-query-js"><%= job.title.upcase %></h2><br>
        </div>
        <div class="job-card__money-and-updated-date-section">
          <div>
          <% if job.hourly_rate? %>
            <h5><%= job.money %>€/hour</h5>
          <% else %>
            <h5><%= job.money %>€ total</h5>
          <% end %>
          </div>
          <div>
            <h5>posted <%= time_ago_in_words(job.created_at) %> ago</h5>
          </div>
        </div>
        <p class="job-card__description highlight-query-js"><%= job.description %></p>
        <ul class="job-card__skills">
          <% job.display_skills.each do |skill| %>
            <li class="job-card__skill"><h5 class="job-card__skill-box highlight-query-js"><%= skill.downcase %></h5></li>
          <% end %>
        </ul>
        <%= link_to "See more", job_path(job), class: "job-card__submit-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= render 'shared/hamburger' %>
<div class="form-page autocomplete-form-js">
  <div class="form-page__form-and-title">
    <h1 class="form-page__title">
      Edit your job
      <div class="form-page__underline"></div>
    </h1>
    <div class="form-page__form">
      <div class="form-page__content">
        <%= render "form" , locals: { job: @job } %>
      </div>
    </div>
  </div>
  <div class="form-page__divider-and-img">
    <div class="form-page__divider--first"></div>
    <div class="form-page__divider--second"></div>
    <div class="form-page__img form-page__img--edit-job"></div>
  </div>
</div>

app/views/jobs/index.html.erb
<%= render 'shared/navbar' %>
<div class="search-bar-and-filters">
  <%= simple_form_for :search, url: jobs_path, html: { class: "search-bar-and-filters__form search-form-js" }, remote: true,  method: :get do |f| %>
    <div class="search-bar-and-filters__search-bar">
      <input type="text" name="query" placeholder="Search through jobs..." class="search-bar-and-filters__search-input refresh-input-js user-input-highlight-js", autocomplete="off", value=<%= params[:query] %>>
      <button class="search-bar-and-filters__search-btn" type="submit">
        <i class="search-bar-and-filters__search-icon fas fa-search"></i>
      </button>
    </div>
    <div class="search-bar-and-filters__filters">
      <div class="search-bar-and-filters__filter-btn">
        <i class="fas fa-filter search-bar-and-filters__filter-icon filter-effect-js"></i>
        <div class="search-bar-and-filters__filter-text filter-effect-js">FILTER</div>
      </div>
      <div class="search-bar-and-filters__filter-options--hidden show-radio-btns-js">
        <%= f.collection_radio_buttons :payment, [["fixed_rate", "Fixed payment"], ["hourly_rate", "Hourly payment"], ["all", "All"]], :first, :last, item_label_class: 'search-bar-and-filters__filter-labels checkbox-label-js', checked: "all" %>
        <div class="search-bar-and-filters__cover search-bar-and-filters__cover--unfolded hide-filter-text-js"></div>
      </div>
    </div>
  <% end %>
</div>
<div class="render-results-js">
  <%= render "index_job", jobs: @jobs, query: params[:query] %>
</div>

app/views/jobs/new.html.erb
<%= render 'shared/hamburger' %>
<div class="form-page autocomplete-form-js">
  <div class="form-page__form-and-title">
    <h1 class="form-page__title">
      Create a new job
      <div class="form-page__underline"></div>
    </h1>
    <div class="form-page__form">
      <div class="form-page__content">
        <%= render "form" , locals: { job: @job } %>
      </div>
    </div>
  </div>
  <div class="form-page__divider-and-img">
    <div class="form-page__divider--first"></div>
    <div class="form-page__divider--second"></div>
    <div class="form-page__img form-page__img--new-job"></div>
  </div>
</div>

app/views/jobs/show.html.erb
<%= render 'shared/hamburger' %>
<div class="job-show-card">
  <div class="job-show-card__back-link">
    <div class="job-show-card__back-arrow">&#10132;</div>
    <%= link_to :back, class: "job-show-card__back-text" do %>
      <h5>Return</h5>
    <% end %>
  </div>
  <div class="job-show-card__content">
    <h1 class="job-show-card__title"><%= @job.title.upcase %></h1>
    <h4 class="job-show-card__description"><%= simple_format @job.description %></h4>
    <div class="job-show-card__icons-section">
      <div class="job-show-card__payment">
        <% if @job.fixed_rate? %>
          <i class="job-show-card__icon fas fa-money-bill-wave-alt"></i><h5><%= @job.money %>€</h5>
        <% else %>
          <i class="job-show-card__icon fas fa-money-bill-wave-alt"></i><h5><%= @job.money %>€/hour</h5>
        <% end %>
      </div>
      <div class="job-show-card__location">
        <i class="job-show-card__icon fas fa-map-marker-alt"></i> <h5><%= @job.location %></h5>
      </div>
      <div class="job-show-card__date">
        <i class="job-show-card__icon fas fa-clock"></i><h5>posted <%= time_ago_in_words(@job.created_at) %> ago</h5>
      </div>
    </div>
    <ul class="job-show-card__skills">
      <h4 class="job-show-card__skill-label"><%= "Skill".pluralize(@job.display_skills.count) %> needed:</h4>
      <% @job.display_skills.each do |skill| %>
        <li class="job-show-card__skill"><h4 class="job-show-card__skill-box"><%= skill.downcase %></h4></li>
      <% end %>
    </ul>
    <% if @job.project.user == current_user %>
      <%= link_to "Edit your job", edit_job_path(@job), class: "job-show-card__edit-btn btn" %>
    <% elsif @job.close? %>
      <button disabled class="job-show-card__disabled-btn btn">Inactive offer</button>
    <% elsif @job.applied?(current_user) %>
      <button disabled class="job-show-card__disabled-btn btn">Application sent</button>
    <% else %>
      <%= link_to "Apply!", new_job_inquiry_path(@job), class: "job-show-card__submit-btn btn bck-btn-reload-js" %>
    <% end %>
    <div class="job-show-card__footer">
      <h5 class="job-show-card__footer-text">
        part of the project <span class="job-show-card__footer-highlight"><%= link_to @job.project.title, project_path(@job.project), class: "job-show-card__footer-link" %></span>
        from <span class="job-show-card__footer-highlight"><%= link_to @job.project.user.username, user_path(@job.project.user), class: "job-show-card__footer-link" %></span>
      </h5>
    </div>
  </div>
</div>