config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  authenticate :user, -> (u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics"
  end

  root to: 'pages#home'
  resources :users, param: :slug do
    resources :mirrors, only: [:update]
    get '/ongoing_projects', to: 'mirrors#ongoing_projects'
    get '/portfolio', to: 'mirrors#past_projects'
  end
  get '/confirmation_pending', to: 'users#after_registration_path'
  resources :projects, param: :slug do
    resources :collabs, only: [:new, :create]
    resources :jobs, only: [:new, :create]
  end
  resources :collabs, only: [:destroy]

  resources :jobs, only: [:show, :destroy, :edit, :update, :index] do
    resources :inquiries, only: [:new, :create]
  end
  resources :inquiries, only: [:show, :destroy, :edit, :update] do
    member do
      patch :change_status
    end
  end
  resources :chatrooms, only: [:show, :index]
  resources :messages, only: [:create]
  resources :events, param: :slug, only: [:show, :index] do
    member do
      post :attend
      post :unattend
    end
  end


  get '/dashboard', to: 'dashboards#dashboard'
  get '/upcoming_projects_dash', to: 'dashboards#upcoming_projects_dash'
  get '/past_projects_dash', to: 'dashboards#past_projects_dash'
  get '/open_jobs_dash', to: 'dashboards#open_jobs_dash'
  get '/close_jobs_dash', to: 'dashboards#close_jobs_dash'
  get '/hold_received_dash', to: 'dashboards#hold_received_dash'
  get '/accepted_received_dash', to: 'dashboards#accepted_received_dash'
  get '/rejected_received_dash', to: 'dashboards#rejected_received_dash'
  get '/upcoming_collabs_dash', to: 'dashboards#upcoming_collabs_dash'
  get '/past_collabs_dash', to: 'dashboards#past_collabs_dash'
  get '/hold_sent_dash', to: 'dashboards#hold_sent_dash'
  get '/accepted_sent_dash', to: 'dashboards#accepted_sent_dash'
  get '/rejected_sent_dash', to: 'dashboards#rejected_sent_dash'

  get '/upcoming_projects', to: 'projects#upcoming_projects'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
end

app/views/shared/_carousel.html.erb
<div class="carousel carousel-container-js">
  <div class="carousel__thumbnails thumbnails-js">
    <% if @project.attachments.attached? %>
      <% if @project.attachments.first.video? %>
        <div class="carousel__mobile-placeholder placeholder-mobile-js">
          <%= cl_video_tag @project.attachments.first.key, controls: true, class: "carousel__mobile-video" %>
        </div>
      <% elsif @project.attachments.first.audio? %>
        <div class="carousel__mobile-placeholder placeholder-mobile-js">
          <div class="carousel__mobile-audio-control-wrapper">
            <%= image_tag asset_path('logo-audio.png'), class: "carousel__audio-poster play-audio-js", alt: "play audio button" %>
            <%= cl_video_tag @project.attachments.first.key, source_types: [:mp3], controls: true, poster: false, class: "carousel__audio-control" %>
          </div>
        </div>
      <% else %>
        <div class="carousel__mobile-placeholder placeholder-mobile-js" data-bs-toggle="modal" data-bs-target="#modalSmallScreen">
          <%= cl_image_tag @project.attachments.first.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], quality: "auto:low", class: "carousel__mobile-img", alt: "project picture", transformation: [{fetch_format: "auto"}, {width: 800, crop: "fill"}] %>
        </div>
      <% end %>
      <% @project_attachments.each do |attachment| %>
        <% if attachment == @project.attachments.first %>
          <picture class="carousel__thumbnail-wrapper carousel__thumbnail--big">
            <source srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" media="(max-width: 992px)" class="carousel__thumbnail">
            <% if attachment.video? %>
              <%= cl_video_tag attachment.key, class: "carousel__thumbnail carousel__thumbnail--poster thumbnail-js" %>
            <% elsif @project.attachments.first.audio? %>
              <%= image_tag asset_path('logo-audio.png'), class: "carousel__thumbnail carousel__thumbnail--poster carousel__thumbnail--img thumbnail-js", alt: "play audio button" %>
              <%= cl_video_tag attachment.key, class: "carousel__thumbnail--video", poster: false %>
            <% else %>
              <%= cl_image_tag attachment.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "carousel__thumbnail carousel__thumbnail--poster carousel__thumbnail--img thumbnail-js", quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 1110, crop: "fill"}], alt: "project picture" %>
            <% end %>
          </picture>
        <% else %>
          <picture class="carousel__thumbnail-wrapper">
            <source srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" media="(max-width: 992px)">
            <% if attachment.video? %>
              <%= cl_video_tag attachment.key, class: "carousel__thumbnail carousel__thumbnail--poster thumbnail-js" %>
            <% elsif attachment.audio? %>
              <%= image_tag asset_path('logo-audio.png'), class: "carousel__thumbnail carousel__thumbnail--poster thumbnail-js", alt: "play audio button" %>
              <%= cl_video_tag attachment.key, poster: false, class: "carousel__thumbnail--video" %>
            <% else %>
              <%= cl_image_tag attachment.key, class: "carousel__thumbnail carousel__thumbnail--poster thumbnail-js", quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 1110, crop: "fill"}], alt: "project picture" %>
            <% end %>
          </picture>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="carousel__mobile-dots">
    <% i = 1 %>
    <% @project.attachments.each do |attachment| %>
      <% if attachment == @project.attachments.first %>
        <div class="carousel__mobile-dot carousel__mobile-dot--active dot-js" data-dot-id="0"></div>
      <% else %>
        <div class="carousel__mobile-dot dot-js" data-dot-id="<%= i %>"></div>
        <% i += 1 %>
      <% end %>
    <% end %>
  </div>
  <div class="carousel__arrows arrows">
    <div class="carousel__arrow--up carousel__arrow--hidden arrow-up-js"></div>
    <div class="carousel__arrow--down carousel__arrow--hidden arrow-down-js"></div>
  </div>
  <div class="carousel__main-slide">
    <div class="carousel__main-container">
      <% if @project.attachments.first.video? %>
        <picture class="carousel__img-video-wrapper img-slide-js">
          <source class="carousel__main-poster" srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" media="(max-width: 992px)">
          <%= cl_video_tag @project.attachments.first.key, controls: true, muted: true, class: "carousel__main-video-poster", alt: "#{@project.title}" %>
        </picture>
      <% elsif @project.attachments.first.audio? %>
        <div class="carousel__main-audio-control-wrapper img-slide-js">
          <%= image_tag asset_path('logo-audio.png'), class: "carousel__main-audio-poster play-audio-js", alt: "#{@project.title}" %>
          <%= cl_video_tag @project.attachments.first.key, source_types: [:mp3], controls: true, poster: false, class: "carousel__main-audio-control" %>
        </div>
      <% else %>
        <picture class="carousel__img-video-wrapper img-slide-js" data-bs-toggle="modal" data-bs-target="#modalBigScreen">
          <source class="carousel__main-poster" srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" media="(max-width: 992px)">
          <%= cl_image_tag @project.attachments.first.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "carousel__main-img-poster", quality: "auto", transformation: [{fetch_format: "auto"}, {width: 1110, crop: "fill"}], alt: "#{@project.title}" %>
        </picture>
      <% end %>
    </div>
  </div>
</div>
<div class="modal fade" id="modalSmallScreen" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content carousel__overlay">
      <div class="modal-body overlay-body-small-screen-js">
        <% if @project.attachments.attached? %>
          <% if @project.attachments.first.video? %>
            <img class="carousel__overlay-poster" src="">
          <% else %>
            <%= cl_image_tag @project.attachments.first.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], quality: "auto", transformation: [{fetch_format: "auto"}], alt: "project picture" %>
          <% end %>
        <% end %>
        <button type="button" class="carousel__overlay-close-btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modalBigScreen" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen ">
    <div class="modal-content carousel__overlay">
      <div class="modal-body carousel__overlay-body overlay-body-big-screen-js">
        <% if @project.attachments.attached? %>
          <% if @project.attachments.first.video? %>
            <img class="carousel__overlay-poster" src="">
          <% else %>
            <%= cl_image_tag @project.attachments.first.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], quality: "auto", transformation: [{fetch_format: "auto"}], alt: "project picture" %>
          <% end %>
        <% end %>
        <button type="button" class="btn-close carousel__overlay-close-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cursor.html.erb
<div class="homepage-cursor homepage-cursor-js">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3500 600">
    <defs>
      <path d="M50,250c0-110.5,89.5-200,200-200s200,89.5,200,200s-89.5,200-200,200S50,360.5,50,250" id="textcircle">
        <animateTransform
                attributeName="transform"
                begin="0s"
                dur="30s"
                type="rotate"
                from="0 250 250"
                to="360 250 250"
                repeatCount="indefinite"
          />
      </path>
    </defs>
    <text dy="20" textLength="1220">
      <textPath class="homepage-cursor__text" xlink:href="#textcircle">hit the click • hit the click •</textPath>
    </text>
  </svg>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-message">
  <div class="footer-message__wrapper">
    <div>* all credits go to the artists:</div>
    <div class="footer-message-dynamic-strings-js">
      <p>no fees</p>
      <p>no ads</p>
      <p>no middleman</p>
      <p>no bullshit</p>
    </div>
    <span class="footer-message__dynamic-text typed-js"></span>
  </div>
</div>
<div class="footer">
  <div class="footer__menus">
    <div class="footer__menu-item" data-bs-toggle="modal" data-bs-target="#modalSupportUs">
      Support us
      <div class="footer__menu-underline"></div>
    </div>
    <div class="footer__menu-item" data-bs-toggle="modal" data-bs-target="#modalFeedback">
      Feedback
      <div class="footer__menu-underline"></div>
    </div>
  </div>
  <div class="footer__brand">InfamousBerlin</div>
</div>

app/views/shared/_hamburger.html.erb
<nav class="hamburger-menu" role='navigation'>
  <div id="menu-toggle" class="hamburger-menu__toggle-sidebar">
    <input type="checkbox" id="checkbox" class="hamburger-menu__checkbox"/>
    <div class="hamburger-menu__screen-blur"></div>
    <span class="hamburger-menu__burger-slice hamburger-menu__burger-slice--top"></span>
    <span class="hamburger-menu__burger-slice hamburger-menu__burger-slice--middle"></span>
    <span class="hamburger-menu__burger-slice hamburger-menu__burger-slice--bottom"></span>
    <ul id="menu" class="hamburger-menu__navigation">
      <li class="hamburger-menu__brand">
        <%= link_to "InfamousBerlin", root_path, class: "hamburger-menu__link" %>
        <div class="hamburger-menu__brand-underline"></div>
      </li>
      <li class="hamburger-menu__sections">
        <ul class="hamburger-menu__section hamburger-menu__section--first-section">
          <li class="hamburger-menu__item"><%= link_to "Events", events_path, class: "hamburger-menu__link" %></li>
          <li class="hamburger-menu__item"><%= link_to "Find talent", users_path, class: "hamburger-menu__link" %></li>
          <li class="hamburger-menu__item"><%= link_to "Find project", upcoming_projects_path, class: "hamburger-menu__link" %></li>
          <li class="hamburger-menu__item"><%= link_to "Find job", jobs_path, class: "hamburger-menu__link" %></li>
        </ul>
        <ul class="hamburger-menu__section hamburger-menu__section--second-section">
          <% if !user_signed_in? %>
            <li class="hamburger-menu__item"><%= link_to "Log in", new_user_session_path, data: {'bs-toggle': "modal", 'bs-target': "#modalLogin"}, class: "hamburger-menu__link" %></li>
            <li class="hamburger-menu__item"><%= link_to "Sign up", new_user_registration_path, class: "hamburger-menu__link" %></li>
          <% else %>
            <li class="hamburger-menu__item"><%= link_to "Dashboard", dashboard_path, class: "hamburger-menu__link" %></li>
            <li class="hamburger-menu__item hamburger-menu__item--messages">
              <%= link_to "Messages", chatrooms_path, class: "hamburger-menu__link" %>
              <% if current_user.unread_messages? %>
                <div class="hamburger-menu__messages-badge"></div>
              <% end %>
            </li>
            <li class="hamburger-menu__item"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "hamburger-menu__link" %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_login_form.html.erb
<div class="modal fade login-modal" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content login-modal__content">
      <div class="modal-header login-modal__header">
        <h5 class="modal-title" id="loginModalLabel">Log in</h5>
        <button type="button" class="btn-close login-modal__close-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "off", class: "form-page__input" },
                        wrapper_html: { class: 'form-page__label' } %>
            <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "off", class: "form-page__input" },
                        wrapper_html: { class: 'form-page__label' } %>
            <%= f.input :remember_me, input_html: { class: "login-modal__checkbox" }, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="login-modal__error-message error-new-session-js"></div>
          <%= link_to "Create an account", new_user_registration_path, class: "login-modal__link" %><br>
          <%= link_to "Forgot your password?", new_password_path(resource_name), class: "login-modal__link" %>
          <div class="modal-footer login-modal__footer">
            <%= f.button :submit, "Log in", class: "btn login-modal__btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="vertical-navbar">
  <% if user_signed_in? %>
    <%= render 'shared/hamburger' %>
  <% else %>
    <ul class="vertical-navbar__menus">
      <li class="vertical-navbar__menu-item"><%= link_to "Sign Up", new_user_registration_path, class: "vertical-navbar__link--sign-up" %></li>
      <li class="vertical-navbar__menu-item-separator">/</li>
      <li class="vertical-navbar__menu-item"><%= link_to "Login", new_user_session_path, class: "vertical-navbar__link", data: {'bs-toggle': "modal", 'bs-target': "#modalLogin"} %></li>
      <li class="vertical-navbar__menu-item-separator">/</li>
      <li class="vertical-navbar__menu-item"><%= link_to "Find talent", users_path, class: "vertical-navbar__link" %></li>
      <li class="vertical-navbar__menu-item-separator">/</li>
      <li class="vertical-navbar__menu-item"><%= link_to "Find project", upcoming_projects_path, class: "vertical-navbar__link" %></li>
      <li class="vertical-navbar__menu-item-separator">/</li>
      <li class="vertical-navbar__menu-item"><%= link_to "Events", events_path, class: "vertical-navbar__link" %></li>
      <li class="vertical-navbar__menu-item-separator">/</li>
      <li class="vertical-navbar__menu-item--brand">
        <%= link_to root_path, class: "vertical-navbar__brand-container" do %>
          <div class="vertical-navbar__brand-text">InfamousBerlin</div>
        <% end %>
      </li>
    </ul>
  <% end %>
</nav>
<%= render 'shared/login_form' %>

app/views/shared/_preloader.html.erb
<div class="preloader preloader--is-visible preloader-js">
  <div class="preloader__text-wrapper">
    <h1 class="preloader__text">InfamousBerlin</h1>
    <div class="preloader__text-cover preloader__text-cover--is-hidding preloader-text-cover-js"></div>
  </div>
</div>

app/views/shared/_tap_btn.html.erb
<div class="mobile-homepage-tap-btn mobile-homepage-tap-btn-js">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 500 600">
    <defs>
      <path d="M50,250c0-110.5,89.5-200,200-200s200,89.5,200,200s-89.5,200-200,200S50,360.5,50,250" id="textcircle">
        <animateTransform
                attributeName="transform"
                begin="0s"
                dur="30s"
                type="rotate"
                from="0 250 250"
                to="360 250 250"
                repeatCount="indefinite"
          />
      </path>
    </defs>
    <text dy="20" textLength="1220">
      <textPath class="mobile-homepage-tap-btn__text" xlink:href="#textcircle">tap to carry on • tap to carry on •</textPath>
    </text>
  </svg>
</div>