config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  authenticate :user, -> (u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics"
  end

  root to: 'pages#home'
  resources :users, param: :slug do
    resources :mirrors, only: [:update]
    get '/ongoing_projects', to: 'mirrors#ongoing_projects'
    get '/portfolio', to: 'mirrors#past_projects'
  end
  get '/confirmation_pending', to: 'users#after_registration_path'
  resources :projects, param: :slug do
    resources :collabs, only: [:new, :create]
    resources :jobs, only: [:new, :create]
  end
  resources :collabs, only: [:destroy]

  resources :jobs, only: [:show, :destroy, :edit, :update, :index] do
    resources :inquiries, only: [:new, :create]
  end
  resources :inquiries, only: [:show, :destroy, :edit, :update] do
    member do
      patch :change_status
    end
  end
  resources :chatrooms, only: [:show, :index]
  resources :messages, only: [:create]
  resources :events, param: :slug, only: [:show, :index] do
    member do
      post :attend
      post :unattend
    end
  end


  get '/dashboard', to: 'dashboards#dashboard'
  get '/upcoming_projects_dash', to: 'dashboards#upcoming_projects_dash'
  get '/past_projects_dash', to: 'dashboards#past_projects_dash'
  get '/open_jobs_dash', to: 'dashboards#open_jobs_dash'
  get '/close_jobs_dash', to: 'dashboards#close_jobs_dash'
  get '/hold_received_dash', to: 'dashboards#hold_received_dash'
  get '/accepted_received_dash', to: 'dashboards#accepted_received_dash'
  get '/rejected_received_dash', to: 'dashboards#rejected_received_dash'
  get '/upcoming_collabs_dash', to: 'dashboards#upcoming_collabs_dash'
  get '/past_collabs_dash', to: 'dashboards#past_collabs_dash'
  get '/hold_sent_dash', to: 'dashboards#hold_sent_dash'
  get '/accepted_sent_dash', to: 'dashboards#accepted_sent_dash'
  get '/rejected_sent_dash', to: 'dashboards#rejected_sent_dash'

  get '/upcoming_projects', to: 'projects#upcoming_projects'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :mirrors, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :collabs, dependent: :destroy
  has_many :members, class_name: 'User', through: :collabs
  has_many_attached :attachments
  enum status: { past: "past", upcoming: "upcoming" }

  validates :title, uniqueness: true,
                    presence: true,
                    case_sensitive: false,
                    format: { without: /(<|>|&)/, message: "cannot include special characters" },
                    length: { maximum: 100, message: "is too long" }
  validates :description, presence: true, format: { without: /(<|>|&)/, message: "cannot include <, >, and &" }
  validates :slug, uniqueness: true, case_sensitive: false
  validates :attachments,
            content_type: {
              in: ['image/png', 'image/jpg', 'image/jpeg', 'video/mp4', 'audio/mpeg'],
              message: ' - wrong format (PNG, JPG, JPEG, MP3 or MP4 only)'
            },
            size: { less_than: 5.megabytes, message: '5MB max' },
            presence: true

  validates_length_of :attachments, maximum: 5, message: "5 files max"

  after_create :renew_slug
  after_create_commit :create_mirror
  before_update :set_slug

  include PgSearch::Model

  pg_search_scope :search_by_title_description_location_category, against: {
    title: "A",
    category: "A",
    description: "B",
    location: "B"
  }, using: {
    tsearch: { prefix: true, any_word: true }
  }

  def to_param
    slug
  end

  def self.list_projects_based_on(params)
    Workflows::ProjectSelector.new.custom_index(params)
  end

  private

  def set_slug
    Services::SlugGenerator.new(string: title, client: self).assign_slug
  end

  def renew_slug
    Services::SlugGenerator.new(string: title, client: self).update_slug
  end

  def create_mirror
    Mirror.create(user: user, project: self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show upcoming_projects]
  before_action :find_project, only: %i[show edit update destroy]

  def show
    @members = @project.members
    @jobs = @project.jobs
    @collab = Collab.new
    @project_formatted_categories = Services::TagsRenderer.new(@project.category).format_tags
    @project_attachments = @project.attachments.includes([:blob])
  end

  def new
    @project = Project.new
    authorize @project
    @location_autocomplete_set = Services::AutocompleteGenerator.new.location_set
    @category_autocomplete_set = Services::AutocompleteGenerator.new.category_set
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def edit
    @location_autocomplete_set = Services::AutocompleteGenerator.new.location_set
    @category_autocomplete_set = Services::AutocompleteGenerator.new.category_set
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to dashboard_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to dashboard_path, notice: 'Project deleted'
  end

  def upcoming_projects
    @projects = Project.list_projects_based_on(params)
    @projects = @projects.search_by_title_description_location_category(params[:query]) if params[:query].present?
    authorize @projects
    respond_to do |format|
      format.html
      format.text do
        render partial: 'search-results.html',
               locals: { projects: @projects, query: params[:query], status: params[:search][:status] }
      end
    end
  end

  private

  def find_project
    @project = Project.find_by!(slug: params[:slug])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:title, :description, :category, :date, :location, :status, attachments: [])
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, remote: true, html: { class: "form-js"} do |f| %>
  <%= f.input :title, label: 'Project title:', wrapper_html: { class: "form-page__project-title" }, label_html: { class: 'form-page__label' }, input_html: { class: 'form-page__input form-page__input--project-title', autocomplete: "off" } %>
  <%= f.input :description, label: 'Describe your project:', wrapper_html: { class: "form-page__project-description" }, label_html: { class: 'form-page__label' }, input_html: { class: 'form-page__input form-page__input--big' } %>
  <div class="form-page__location-date-status-wrapper">
    <%= f.input :location, label: 'Location:', wrapper_html: { data: { set: @location_autocomplete_set.to_json }, class: "form-page__project-location search-data-js" }, label_html: { class: 'form-page__label' }, input_html: { class: 'form-page__input search-input-js' } %>
    <%= f.input :date, as: :string, label: 'When?', wrapper_html: { class: "form-page__date" }, label_html: { class: 'form-page__label' }, input_html: { class: "form-page__input datepicker datepicker-js" } %>
    <%= f.input :status, label: 'Project status:', as: :select, collection: @project.class.statuses.keys, include_blank: false, wrapper_html: { class: "form-page__status" }, label_html: { class: 'form-page__label' }, input_html: { class: "form-page__input" } %>
  </div>
  <%= f.input :category, wrapper_html: { class: "form-page__category-hidden-field" }, input_html: { class: "attributes_hidden_field_js" } %>
  <div class="form-page__categories-custom">
    <div class="form-page__add-categories search-data-js" data-set="<%= @category_autocomplete_set.to_json %>">
      <label for="fname" class="form-page__add-categories-label form-page__label">Add a project category:</label>
      <div class="form-page__add-categories-input-and-btn">
        <input type="text" id="fname" class="form-page__add-categories-input form-page__input search-input-js attribute-value-js"></input>
        <div class="form-page__add-categories-btn btn-add-attribute-js">Add</div>
      </div>
    </div>
    <div>
      <label class="form-page__categories-list-label form-page__label">Category list:</label>
      <ol class="form-page__categories-list-items attributes-list-js">
      </ol>
    </div>
  </div>
  <div class="form-page__preview-photos placeholder-preview-js">
    <% if @project.attachments.attached? %>
      <% @project.attachments.each do |attachment| %>
        <div class="form-page__preview-photo-wrapper">
          <% if attachment.blob.content_type == "image/jpeg" %>
            <%= cl_image_tag attachment.key, class: "form-page__preview-photo" %>
          <% elsif attachment.blob.content_type == "video/mp4" %>
            <%= cl_video_tag attachment.key, controls: true, muted: true, class: "form-page__preview-photo" %>
          <% else %>
            <%= cl_video_tag attachment.key, source_types: [:mp3], controls: true, poster: true, class: "form-page__preview-photo form-page__preview-photo--audio-poster" %>
          <% end %>
          <div class="form-page__preview-delete-wrapper delete-signed-id-js">
            <div class="form-page__preview-delete-btn">&#x2716;</div>
          </div>
          <%= f.hidden_field :attachments, multiple: true, value: attachment.signed_id, id: "project-photo-signed-id" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <label for="project_attachments" class="form-page__label form-page__label-new-project-attachment">
    <i class="form-page__icon-new-project-attachment fas fa-paperclip"></i>
    <a class="form-page__link-new-project-attachment">select attachment(s)</a>
  </label>
  <%= f.input :attachments, as: :file, label: false, :input_html => { :multiple => true, accept: ".png, .jpg, .jpeg, .mp4, .mp3", class: "form-page__new-project-attachment--hidden project-attachments-upload-btn-js" } %>

  <%= f.submit "Save!", class: "form-page__submit-btn form-btn-js" %>
  <button class="form-page__loading-btn form-page__loading-btn--hidden form-btn-js" type="button" disabled>
    <span class="spinner-border" role="status" aria-hidden="true"></span>
    Loading...
  </button>
<% end %>

app/views/projects/_project.html.erb
<div data-project=<%= @project.id %>>
  <% if !user_signed_in? %>
    <%= link_to new_user_session_path, data: {toggle: "modal", target: "#modalLogin"} do %>
      <button type="button" class="ml-5 btn btn-success" >
        Apply now!
      </button>
    <% end %>
  <% elsif !current_user.applied?(@project.id) %>
    <button type="button" class="ml-5 btn btn-success" data-toggle="modal" data-target="#confirmApplicationModal" >
      Apply now!
    </button>
  <% else %>
    <button type="button" class="ml-5 btn btn-secondary" >
      Application send
    </button>
  <% end %>
</div>

<div class="modal fade" id="confirmApplicationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your application to <%= @project.user.username %>'s project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Please confirm that you would like to apply to:<br><br>
        <ul><%= @project.title %></ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= link_to "Apply", apply_project_path(@project.slug), class: "btn btn-success", method: :post, remote: true %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_search-results.html.erb
<div class="search-results-js">
  <% if query.blank? %>
    <h4 class="placeholder-numbers-results"></h4>
  <% else %>
    <h4 class="numbers-results"><%= projects.count %> <%= "project".pluralize(projects.count)%> matching your search for "<%= query %>" in <%= status %> projects</h4>
  <% end %>
  <div class="project-results-grid">
    <% @projects.each do |project| %>
      <div class="project-card__wrapper align-items-on-safari-js">
        <div class="project-card__item">
          <%= link_to project_path(project.slug), class: "project-card__link" do  %>
            <div class="project-card__title-and-ribbon">
              <h4 class="project-card__title highlight-query-js">
                <%= project.title %>
              </h4>
              <% if project.upcoming? %>
                <div class="project-card__ribbon">UPCOMING</div>
              <% end %>
            </div>
            <div class="project-card__img-and-avatar">
              <div class="project-card__img-wrapper">
                <% if project.attachments.first.image? %>
                  <%= cl_image_tag project.attachments.first.key, class: "project-card__img", quality: "auto:low", alt: "project picture", transformation: [{fetch_format: "auto"}, {width: 400, crop: "fill"}] %>
                <% elsif project.attachments.first.audio? %>
                  <%= image_tag asset_path('logo-audio.png'), class: "project-card__img", alt: "play audio button", transformation: [{fetch_format: "auto"}, {width: 400, crop: "fill"}] %>
                <% else %>
                  <%= cl_video_tag project.attachments.first.key, class: "project-card__img" %>
                <% end %>
              </div>
              <div class="project-card__avatar">
                <%= cl_image_tag project.user.photo.key, quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 100, crop: "fill"}], class: "project-card__avatar-img", alt: "user profile picture" %>
              </div>
            </div>
            <div class="project-card__description highlight-query-js"><%= project.description %></div>
          <% end %>
          <div class="project-card__shadow"></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'shared/hamburger' %>
<div class="form-page autocomplete-form-js">
  <div class="form-page__form-and-title">
    <h1 class="form-page__title">
      Edit your project
      <div class="form-page__underline"></div>
    </h1>
    <div class="form-page__form">
      <div class="form-page__content">
        <%= render "form" , locals: { project: @project } %>
      </div>
    </div>
  </div>
  <div class="form-page__divider-and-img">
    <div class="form-page__divider--first"></div>
    <div class="form-page__divider--second"></div>
    <div class="form-page__img form-page__img--edit-project"></div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'shared/hamburger' %>
<div class="form-page autocomplete-form-js">
  <div class="form-page__form-and-title">
    <h1 class="form-page__title">
      Create a new project
      <div class="form-page__underline"></div>
    </h1>
    <div class="form-page__form">
      <div class="form-page__content">
        <%= render "form" , locals: { project: @project } %>
      </div>
    </div>
  </div>
  <div class="form-page__divider-and-img">
    <div class="form-page__divider--first"></div>
    <div class="form-page__divider--second"></div>
    <div class="form-page__img form-page__img--new-project"></div>
  </div>
</div>

app/views/projects/show.html.erb
<%= render 'shared/navbar' %>
<div class="carousel-and-project-details__wrapper">
  <div class="carousel-and-project-details">
    <%= render 'shared/carousel' %>
    <div class="carousel-and-project-details__title-and-owner-wrapper">
      <div class="carousel-and-project-details__title-and-owner">
        <div class="carousel-and-project-details__title"><%= @project.title %></div>
        <h3 class="carousel-and-project-details__owner">by <%= link_to @project.user.username, user_path(@project.user), class:"carousel-and-project-details__owner-link" %></h3>
      </div>
      <div class="carousel-and-project-details__members">
        <% if @members.any? %>
          <div class="carousel-and-project-details__label-and-avatars">
            <div class="carousel-and-project-details__label"><%= 'Member'.pluralize(@members.count) %>:</div>
            <div class="carousel-and-project-details__avatars">
              <% @members.first(5).each do |member| %>
                <div class="avatars-member-stack" data-bs-toggle="modal" data-bs-target="#membersList">
                  <% if member.photo.attached? %>
                    <%= cl_image_tag member.photo.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "avatars-member-stack__img", quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 70, crop: "fill"}], alt: "project member profile picture" %>
                  <% else %>
                    <%= image_tag asset_path('logo.png'), class: "avatars-member-stack__img", alt: "project member profile picture" %>
                  <% end %>
                </div>
              <% end %>
              <% if @members.size > 5 %>
                <div class="avatars-member-stack" data-bs-toggle="modal" data-bs-target="#membersList">
                  <p class="avatars-member-stack__extra-icon">...</p>
                </div>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="carousel-and-project-details__avatars-placeholder"></div>
        <% end %>
        <div>
        <% if @project.user == current_user %>
          <div class="carousel-and-project-details__new-member-btn-form">
            <button class="carousel-and-project-details__btn-covering btn btn-covering-js">Add member</button>
            <%= simple_form_for [ @project, @collab ], remote: true do |f| %>
              <div class="new-member-form new-member-form-js">
                <div class="new-member-form__content">
                  <div class="new-member-form__field">
                    <label class="new-member-form__label string optional" for="project_member">Add member's username</label>
                    <input type="text" name="project[member]" id="project_member" class="new-member-form__input form-control string optional" autocomplete="off">
                  </div>
                  <%= f.submit "+", class: "new-member-form__btn" %>
                </div>
              </div>
              <% if @collab.errors.any? %>
                <% @collab.errors.full_messages.each do |message| %>
                  <p class="new-member-form__error"><%= message %></p>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
      <div>
        <div class="carousel-and-project-details__jobs">
          <% if @project.user == current_user %>
            <%= link_to new_project_job_path(@project), class:"carousel-and-project-details__jobs-link" do %>
              <button class="carousel-and-project-details__jobs-btn">Add job</button>
            <% end %>
            <% if @jobs.any? %>
              <button class="carousel-and-project-details__talent-eye-btn" data-bs-toggle="modal" data-bs-target="#jobsList">
                <i class="fas fa-eye"></i>
              </button>
            <% end %>
          <% elsif @jobs.any? %>
              <button class="carousel-and-project-details__talent-btn" data-bs-toggle="modal" data-bs-target="#jobsList">Looking for talents!</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="project-description-date-categories-location">
    <div class="project-date-categories-location">
      <div class="project-location">
        <% if @project.location? %>
          <i class="fas fa-map-marker-alt project-date-categories-location__icon"></i>
          <div class="project-date-categories-location__details"><%= @project.location %></div>
        <% end %>
      </div>
      <div class="project-date">
        <% if @project.date? %>
          <i class="fas fa-calendar-day project-date-categories-location__icon"></i>
          <div class="project-date-categories-location__details"><%= @project.date.strftime("%d/%m/%Y") %></div>
        <% end %>
      </div>
      <div class="project-category">
        <% if @project.category? %>
        <i class="fas fa-folder-open project-date-categories-location__icon"></i>
          <% @project_formatted_categories.each do |cat| %>
            <div class="project-category__skill-box"><%= cat %></div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="project-description">
      <div class="project-description__title" id="bottom-page">Description</div>
      <h4 class="project-description__text"><%= simple_format @project.description %></h4>
    </div>
  </div>
</div>
<div>
  <a href="#bottom-page">
    <div class="arrow-bottom-page">
      <ul class="arrow-bottom-page__sticks">
        <li class="arrow-bottom-page__stick arrow-bottom-page__stick--left"></li>
        <li class="arrow-bottom-page__stick arrow-bottom-page__stick--right"></li>
      </ul>
    </div>
  </a>
</div>
<div class="modal fade" id="membersList" tabindex="-1" aria-labelledby="membersModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content members-modal">
      <div class="modal-header members-modal__header">
        <h5 class="modal-title" id="membersModalLabel">Group members</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="members-modal__project-owner">
        <div class="members-modal__title-wrapper">
          <div class="members-modal__title">Project owner:</div>
          <div class="members-modal__underline"></div>
        </div>
        <div class="members-modal__avatar-and-name">
          <div class="member-modal-avatar__frame">
            <%= link_to user_path(@project.user) do %>
              <%= cl_image_tag @project.user.photo.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "member-modal-avatar__img", quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 100, crop: "fill"}] %>
            <% end %>
          </div>
          <%= link_to @project.user.username, user_path(@project.user), class:"member-modal__username" %>
        </div>
      </div>
      <div class="modal-body">
        <div class="members-modal__underlined-subtitle-wrapper">
          <div class="members-modal__subtitle">Additional <%= 'member'.pluralize(@members.count) %>:</div>
          <div class="members-modal__sub-underline"></div>
        </div>
        <% @members.each do |member| %>
          <div class="members-modal__member">
            <div class="member-modal-avatar__frame">
              <%= link_to user_path(member.slug) do %>
                <%= cl_image_tag member.photo.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], class: "member-modal-avatar__img", quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 100, crop: "fill"}], alt: "project member profile picture" %>
              <% end %>
            </div>
            <%= link_to member.username, user_path(member.slug), class:"member-modal__username" %>
            <% if @project.user == current_user %>
              <%= link_to collab_path(member.find_collab_within(@project.id)), class:"member-modal__delete", method: :delete, remote: true do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="jobsList" tabindex="-1" aria-labelledby="jobsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content jobs-modal">
      <div class="modal-header jobs-modal__header">
        <h5 class="modal-title" id="jobsModalLabel">Open jobs</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body jobs-modal__records">
        <% @jobs.each do |job| %>
          <%= link_to job_path(job), class: "jobs-modal__link" do %>
            <div class="jobs-modal__record">
              <h4 class="jobs-modal__title"><%= job.title.downcase %> job in <%= job.location %></h4>
              <div class="jobs-modal__days-and-arrow">
                <p class="jobs-modal__days">(published <%= time_ago_in_words(job.created_at) %> ago)</p>
                <div class="jobs-modal__arrow">
                  <i class="fas fa-arrow-right jobs-modal__icon"></i>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if !user_signed_in? %>
  <%= render 'shared/login_form' %>
<% end %>

app/views/projects/upcoming_projects.html.erb
<%= render 'shared/navbar' %>
<div class="search-bar-and-filters bck-btn-reload-js">
  <%= simple_form_for :search, url: upcoming_projects_path, html: { class: "search-bar-and-filters__form search-form-js"}, remote: true, method: :get do |f| %>
    <div class="search-bar-and-filters__search-bar">
      <input type="text" name="query" placeholder="Search through projects..." class="search-bar-and-filters__search-input refresh-input-js user-input-highlight-js" autocomplete="off">
      <button class="search-bar-and-filters__search-btn" type="submit">
        <i class="search-bar-and-filters__search-icon fas fa-search"></i>
      </button>
    </div>
    <div class="search-bar-and-filters__filters">
      <div class="search-bar-and-filters__filter-btn">
        <i class="fas fa-filter search-bar-and-filters__filter-icon filter-effect-js"></i>
        <div class="search-bar-and-filters__filter-text filter-effect-js">FILTER</div>
      </div>
      <div class="search-bar-and-filters__filter-options--hidden show-radio-btns-js">
        <%= f.collection_radio_buttons :status, [["upcoming", "Upcoming projects"], ["past", "Past projects"], ["all", "All"]], :first, :last, item_label_class: 'search-bar-and-filters__filter-labels checkbox-label-js', checked: "upcoming" %>
        <div class="search-bar-and-filters__cover search-bar-and-filters__cover--unfolded hide-filter-text-js"></div>
      </div>
    </div>
  <% end %>
</div>
<div class="render-results-js">
  <%= render "search-results", projects: @projects, query: params[:query] %>
</div>