config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  authenticate :user, -> (u) { u.admin? } do
    mount ActiveAnalytics::Engine, at: "analytics"
  end

  root to: 'pages#home'
  resources :users, param: :slug do
    resources :mirrors, only: [:update]
    get '/ongoing_projects', to: 'mirrors#ongoing_projects'
    get '/portfolio', to: 'mirrors#past_projects'
  end
  get '/confirmation_pending', to: 'users#after_registration_path'
  resources :projects, param: :slug do
    resources :collabs, only: [:new, :create]
    resources :jobs, only: [:new, :create]
  end
  resources :collabs, only: [:destroy]

  resources :jobs, only: [:show, :destroy, :edit, :update, :index] do
    resources :inquiries, only: [:new, :create]
  end
  resources :inquiries, only: [:show, :destroy, :edit, :update] do
    member do
      patch :change_status
    end
  end
  resources :chatrooms, only: [:show, :index]
  resources :messages, only: [:create]
  resources :events, param: :slug, only: [:show, :index] do
    member do
      post :attend
      post :unattend
    end
  end


  get '/dashboard', to: 'dashboards#dashboard'
  get '/upcoming_projects_dash', to: 'dashboards#upcoming_projects_dash'
  get '/past_projects_dash', to: 'dashboards#past_projects_dash'
  get '/open_jobs_dash', to: 'dashboards#open_jobs_dash'
  get '/close_jobs_dash', to: 'dashboards#close_jobs_dash'
  get '/hold_received_dash', to: 'dashboards#hold_received_dash'
  get '/accepted_received_dash', to: 'dashboards#accepted_received_dash'
  get '/rejected_received_dash', to: 'dashboards#rejected_received_dash'
  get '/upcoming_collabs_dash', to: 'dashboards#upcoming_collabs_dash'
  get '/past_collabs_dash', to: 'dashboards#past_collabs_dash'
  get '/hold_sent_dash', to: 'dashboards#hold_sent_dash'
  get '/accepted_sent_dash', to: 'dashboards#accepted_sent_dash'
  get '/rejected_sent_dash', to: 'dashboards#rejected_sent_dash'

  get '/upcoming_projects', to: 'projects#upcoming_projects'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :mirrors, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :collabs, dependent: :destroy
  has_many :members, class_name: 'User', through: :collabs
  has_many_attached :attachments
  enum status: { past: "past", upcoming: "upcoming" }

  validates :title, uniqueness: true,
                    presence: true,
                    case_sensitive: false,
                    format: { without: /(<|>|&)/, message: "cannot include special characters" },
                    length: { maximum: 100, message: "is too long" }
  validates :description, presence: true, format: { without: /(<|>|&)/, message: "cannot include <, >, and &" }
  validates :slug, uniqueness: true, case_sensitive: false
  validates :attachments,
            content_type: {
              in: ['image/png', 'image/jpg', 'image/jpeg', 'video/mp4', 'audio/mpeg'],
              message: ' - wrong format (PNG, JPG, JPEG, MP3 or MP4 only)'
            },
            size: { less_than: 5.megabytes, message: '5MB max' },
            presence: true

  validates_length_of :attachments, maximum: 5, message: "5 files max"

  after_create :renew_slug
  after_create_commit :create_mirror
  before_update :set_slug

  include PgSearch::Model

  pg_search_scope :search_by_title_description_location_category, against: {
    title: "A",
    category: "A",
    description: "B",
    location: "B"
  }, using: {
    tsearch: { prefix: true, any_word: true }
  }

  def to_param
    slug
  end

  def self.list_projects_based_on(params)
    Workflows::ProjectSelector.new.custom_index(params)
  end

  private

  def set_slug
    Services::SlugGenerator.new(string: title, client: self).assign_slug
  end

  def renew_slug
    Services::SlugGenerator.new(string: title, client: self).update_slug
  end

  def create_mirror
    Mirror.create(user: user, project: self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :confirmable, :recoverable

  has_many :projects, dependent: :destroy
  has_many :collabs, dependent: :destroy
  has_many :member_projects, class_name: 'Project', through: :collabs, source: :project
  has_many :mirrors, dependent: :destroy
  has_many :inquiries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :authored_chatrooms, class_name: 'Chatroom', foreign_key: 'author_id'
  has_many :received_chatrooms, class_name: 'Chatroom', foreign_key: 'receiver_id'
  has_one_attached :photo

  validates :slug, uniqueness: true, case_sensitive: false
  validates :username, uniqueness: true,
                       case_sensitive: false,
                       presence: true,
                       format: { without: /(<|>|&)/, message: "cannot include special characters" },
                       length: { maximum: 100, message: "is too long" }
  validates :bio, format: { without: /(<|>|&)/, message: "cannot include <, >, and &" }
  validates :password, presence: true, length: { minimum: 6, maximum: 128 }, unless: proc { |a| a.password.nil? }
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :photo, size: { less_than: 5.megabytes, message: '5MB max' }

  validates :website, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://example.com)" }
  validates :facebook, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?facebook\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://facebook.com/example)" }
  validates :instagram, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?instagram\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://instagram.com/example)" }
  validates :soundcloud, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?soundcloud\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://soundcloud.com/example)" }
  validates :youtube, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?youtube\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://youtube.com/example)" }
  validates :mixcloud, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?mixcloud\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://mixcloud.com/example)" }
  validates :twitter, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/(www\.)?twitter\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://twitter.com/example)" }
  validates :linkedin, format: { with: /(^$)|(\A(ht|f)tp(s?)\:\/\/([a-zA-Z]*\.)?linkedin\.com[0-9a-zA-Z]*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?\z)/, message: "- please enter a valid url (https://linkedin.com/in/example)" }

  after_create :renew_slug
  before_update :set_slug
  after_create :send_confirmation_email
  after_commit :add_default_img, on: [:create]

  include PgSearch::Model

  pg_search_scope :search_by_username_bio_skills_title, against: {
    username: "A",
    skills: "A",
    title: "A",
    bio: "B"
  }, using: {
    tsearch: {
      prefix: true,
      any_word: true
    }
  }

  def contact_info?
    Workflows::UserContext.new(self).contact_info?
  end

  def unread_messages?
    Workflows::UserContext.new(self).unread_messages?
  end

  def default_profile_pic?
    Workflows::UserContext.new(self).default_profile_pic?
  end

  def self.list_user_index
    Workflows::UserContext.new(nil).list_profiles
  end

  def to_param
    slug
  end

  def find_collab_within(project_id)
    Workflows::UserContext.new(self).find_collab_within(project_id)
  end

  private

  def set_slug
    Services::SlugGenerator.new(string: username, client: self).assign_slug
  end

  def renew_slug
    Services::SlugGenerator.new(string: username, client: self).update_slug
  end

  def send_confirmation_email
    send_confirmation_instructions
  end

  def add_default_img
    Workflows::UserContext.new(self).add_default_img
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :find_different_project_types_instances,
                only: %i[dashboard open_jobs_dash close_jobs_dash hold_received_dash accepted_received_dash rejected_received_dash]
  before_action :find_different_job_types_instances,
                only: %i[dashboard hold_received_dash accepted_received_dash rejected_received_dash]


  def dashboard
    find_different_collab_types_instances
    find_different_received_inquiry_types_instances
    find_different_sent_inquiry_types_instances
  end

  def upcoming_projects_dash
    @projects = Workflows::DashboardRenderer.new.projects_for(current_user, "upcoming")
    render_dashboard_partial_for("projects")
  end

  def past_projects_dash
    @projects = Workflows::DashboardRenderer.new.projects_for(current_user, "past")
    render_dashboard_partial_for("projects")
  end

  def open_jobs_dash
    @jobs = Workflows::DashboardRenderer.new.jobs_for(@project_ids, "open")
    render_dashboard_partial_for("jobs")
  end

  def close_jobs_dash
    @jobs = Workflows::DashboardRenderer.new.jobs_for(@project_ids, "close")
    render_dashboard_partial_for("jobs")
  end

  def upcoming_collabs_dash
    @collabs = Workflows::DashboardRenderer.new.project_collabs_for(current_user, "upcoming")
    render_dashboard_partial_for("collabs")
  end

  def past_collabs_dash
    @collabs = Workflows::DashboardRenderer.new.project_collabs_for(current_user, "past")
    render_dashboard_partial_for("collabs")
  end

  def hold_received_dash
    @inquiries = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "on_hold")
    render_dashboard_partial_for("received")
  end

  def accepted_received_dash
    @inquiries = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "accepted")
    render_dashboard_partial_for("received")
  end

  def rejected_received_dash
    @inquiries = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "rejected")
    render_dashboard_partial_for("received")
  end

  def hold_sent_dash
    @inquiries = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "on_hold")
    render_dashboard_partial_for("sent")
  end

  def accepted_sent_dash
    @inquiries = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "accepted")
    render_dashboard_partial_for("sent")
  end

  def rejected_sent_dash
    @inquiries = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "rejected")
    render_dashboard_partial_for("sent")
  end

  private

  def find_different_project_types_instances
    @upcoming_project = Workflows::DashboardRenderer.new.projects_for(current_user, "upcoming")
    @past_project = Workflows::DashboardRenderer.new.projects_for(current_user, "past")
    @projects = Workflows::DashboardRenderer.new.display_by_order_of_relevance(
      { first: @upcoming_project,
        second: @past_project }
    )
    @project_ids = [@upcoming_project.ids, @past_project.ids].flatten
  end

  def find_different_job_types_instances
    @open_jobs = Workflows::DashboardRenderer.new.jobs_for(@project_ids, "open")
    @close_jobs = Workflows::DashboardRenderer.new.jobs_for(@project_ids, "close")
    @job_ids = [@open_jobs.ids, @close_jobs.ids].flatten
  end

  def find_different_collab_types_instances
    @upcoming_project_collabs = Workflows::DashboardRenderer.new.project_collabs_for(current_user, "upcoming")
    @past_project_collabs = Workflows::DashboardRenderer.new.project_collabs_for(current_user, "past")
    @collabs = Workflows::DashboardRenderer.new.display_by_order_of_relevance(
      { first: @upcoming_project_collabs,
        second: @past_project_collabs }
    )
    @collab_ids = [@upcoming_project_collabs.ids, @past_project_collabs.ids].flatten
  end

  def find_different_received_inquiry_types_instances
    @hold_received_applications = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "on_hold")
    @accepted_received_applications = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "accepted")
    @rejected_received_applications = Workflows::DashboardRenderer.new.received_inquiries_for(@job_ids, "rejected")
    @received_inquiry_ids = [@hold_received_applications.ids, @accepted_received_applications.ids, @rejected_received_applications.ids].flatten
  end

  def find_different_sent_inquiry_types_instances
    @hold_sent_applications = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "on_hold")
    @accepted_sent_applications = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "accepted")
    @rejected_sent_applications = Workflows::DashboardRenderer.new.sent_inquiries_for(current_user, "rejected")
    @inquiries = Workflows::DashboardRenderer.new.display_by_order_of_relevance(
      { first: @hold_sent_applications,
        second: @accepted_sent_applications,
        third: @rejected_sent_applications }
    )
    @sent_inquiry_ids = [@hold_sent_applications.ids, @accepted_sent_applications.ids, @rejected_sent_applications.ids].flatten
  end

  def render_dashboard_partial_for(partial_type)
    respond_to do |format|
      format.text { render partial: "#{partial_type}_dash.html" }
    end
  end
end

app/views/dashboards/_received_dash.html.erb
<div class="dashboard__inquiry-list slider-js inquiry-dash-js">
  <h4 class="dashboard__mobile-title">Applications</h4>
  <% @inquiries.each do |inquiry| %>
    <div class="dashboard__inquiry-list-item">
      <h4 class="dashboard__inquiry-record-date"><%= inquiry.created_at.strftime("%d/%m") %></h4>
      <h4 class="dashboard__inquiry-record-text">
        Application from user
        <%= link_to inquiry.user.username, user_path(inquiry.user.slug), class: "dashboard__inquiry-record-link" %> to project
        <%= link_to inquiry.job.project.title, project_path(inquiry.job.project.slug), class: "dashboard__inquiry-record-link" %>
      </h4>
      <%= link_to inquiry_path(inquiry), class:"dashboard__inquiry-record-btn dashboard__inquiry-record-btn--show", id: "test-id-on-hold-inquiry" do %>
        <i class="dashboard__inquiry-record-icon dashboard__inquiry-record-icon--show fas fa-arrow-right"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboards/_sent_dash.html.erb
<div class="dashboard__inquiry-list slider-js inquiry-dash-js">
  <h4 class="dashboard__mobile-title">Applications</h4>
  <% @inquiries.each do |inquiry| %>
    <div class="dashboard__inquiry-list-item">
      <h4 class="dashboard__inquiry-record-date"><%= inquiry.created_at.strftime("%d/%m") %></h4>
      <h4 class="dashboard__inquiry-record-text">
        Application to project
        <%= link_to inquiry.job.project.title, project_path(inquiry.job.project.slug), class: "dashboard__inquiry-record-link" %> owned by user
        <%= link_to inquiry.job.project.user.username, user_path(inquiry.job.project.user.slug), class: "dashboard__inquiry-record-link" %>
      </h4>
      <% if inquiry.on_hold? %>
        <div class="dashboard__sent-inquiries-icons">
          <%= link_to inquiry_path(inquiry), class:"dashboard__inquiry-record-btn dashboard__inquiry-record-btn dashboard__inquiry-record-btn--show" do %>
            <i class="dashboard__inquiry-record-icon fas fa-arrow-right"></i>
          <% end %>
          <%= link_to edit_inquiry_path(inquiry), class:"dashboard__inquiry-record-btn dashboard__inquiry-record-btn dashboard__inquiry-record-btn--edit" do %>
            <i class="dashboard__inquiry-record-icon fas fa-pencil-alt"></i>
          <% end %>
          <%= link_to inquiry_path(inquiry), class:"dashboard__inquiry-record-btn dashboard__inquiry-record-btn dashboard__inquiry-record-btn--delete", method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="dashboard__inquiry-record-icon fas fa-trash"></i>
          <% end %>
        </div>
      <% else %>
        <%= link_to inquiry_path(inquiry), class:"dashboard__inquiry-record-btn dashboard__inquiry-record-btn--show" do %>
          <i class="dashboard__inquiry-record-icon fas fa-arrow-right"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboards/dashboard.html.erb
<%= render 'shared/hamburger' %>
<div class="dashboard__container">
  <h1 class="dashboard__underlined-title">
    Dashboard
    <div class="dashboard__underline"></div>
  </h1>
  <div class="dashboard__content">
    <div class="dashboard__avatar_and_username">
      <div class="avatar-dashboard">
        <div class="avatar-dashboard__wrapper">
          <h3 class="avatar-dashboard__username"><%= current_user.username %></h3>
          <div class="avatar-dashboard__frame">
            <% if !current_user.default_profile_pic? %>
              <%= link_to user_path(current_user.slug), class: "avatar-dashboard__img-link" do %>
                <%= cl_image_tag current_user.photo.key, quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 300, crop: "fill"}], class: "avatar-dashboard__img", alt: "user profile picture" %>
              <% end %>
            <% else %>
              <%= link_to edit_user_path(current_user.slug, anchor: "picture-anchor"), class: "avatar-dashboard__img-link" do %>
                <div class="avatar-dashboard__img-reminder-text">Upload a picture!</div>
                <div class="avatar-dashboard__img-reminder"></div>
                <%= cl_image_tag current_user.photo.key, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'], quality: "auto:low", transformation: [{fetch_format: "auto"}, {width: 300, crop: "fill"}], class: "avatar-dashboard__img", alt: "user profile picture" %>
              <% end %>
            <% end %>
          </div>
          <h5 class="avatar-dashboard__user-title"><%= current_user.title %></h5>
        </div>
      <div>
    </div>
  </div>
  <div class="dashboard__line-separator"></div>
  <div class="dashboard__upper-links">
    <%= link_to user_path(current_user.slug), class: "dashboard__upper-link" do %>
      <h3 class="dashboard__upper-link-text">
        Visit your profile
        <div class="dashboard__upper-link-underline dashboard__upper-link-underline--green"></div>
      </h3>
    <% end %>
    <br>
    <%= link_to edit_user_path(current_user.slug), class: "dashboard__upper-link" do %>
      <h3 class="dashboard__upper-link-text dashboard__upper-link-text--edit">
        Edit your profile
        <div class="dashboard__upper-link-underline dashboard__upper-link-underline--gray"></div>
        <% if current_user.bio.blank? %>
          <div class="dashboard__upper-link-uncomplete-badge"></div>
          <div class="dashboard__upper-link-uncomplete-message">Fill up your profile to get better exposure through searches!</div>
          <div class="dashboard__upper-link-uncomplete-placeholder"></div>
        <% end %>
      </h3>
    <% end %>
    <br>
    <% if policy(Project).create? %>
      <%= link_to new_project_path, class: "dashboard__upper-link" do %>
        <h3 class="dashboard__upper-link-text">
          Add a new project
          <div class="dashboard__upper-link-underline dashboard__upper-link-underline--green"></div>
        </h3>
      <% end %>
    <% end %>
  </div>
</div>
<div class="dashboard__line-separator"></div>
<div class="dashboard__menus-wrapper">
  <input type="checkbox" id="checkbox_toggle">
  <label class="dashboard__mobile-menu-arrow" for="checkbox_toggle"></label>
  <div class="dashboard__mobile-menu-more mobile-dropdown-arrow-js"></div>
  <ul class="dashboard__menus">
    <% if @project_ids.any? %>
      <li class="dashboard__menu">
        <div class="dashboard__menu-title" >Projects</div>
        <div class="dashboard__menu-links">
          <% if @upcoming_project.present? %>
            <%= link_to "Upcoming", upcoming_projects_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @past_project.present? %>
            <%= link_to "Past", past_projects_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
        </div>
      </li>
    <% end %>
    <% if @job_ids.any? %>
      <li class="dashboard__menu dashboard__menu--jobs">
        <div class="dashboard__menu-title" >Jobs</div>
        <div class="dashboard__menu-links">
          <% if @open_jobs.present? %>
            <%= link_to "Open", open_jobs_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @close_jobs.present? %>
            <%= link_to "Close", close_jobs_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
        </div>
      </li>
    <% end %>
    <% if @received_inquiry_ids.any? %>
      <li class="dashboard__menu">
        <div class="dashboard__menu-title" id="test-id-inquiries-menu" >Applications received</div>
        <div class="dashboard__menu-links">
          <% if @hold_received_applications.present? %>
            <%= link_to "On hold", hold_received_dash_path, class: "dashboard__menu-link dropdown-links-js", id:"test-id-on-hold-inquiries-menu", remote: true %>
          <% end %>
          <% if @accepted_received_applications.present? %>
            <%= link_to "Accepted", accepted_received_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @rejected_received_applications.present? %>
            <%= link_to "Rejected", rejected_received_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
        </div>
      </li>
    <% end %>
    <% if @collab_ids.any? %>
      <li class="dashboard__menu">
        <div class="dashboard__menu-title" >Collabs</div>
        <div class="dashboard__menu-links">
          <% if @upcoming_project_collabs.present? %>
            <%= link_to "Upcoming", upcoming_collabs_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @past_project_collabs.present? %>
            <%= link_to "Past", past_collabs_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
        </div>
      </li>
    <% end %>
    <% if @sent_inquiry_ids.any? %>
      <li class="dashboard__menu">
        <div class="dashboard__menu-title" >Applications sent</div>
        <div class="dashboard__menu-links">
          <% if @hold_sent_applications.present? %>
            <%= link_to "On hold", hold_sent_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @accepted_sent_applications.present? %>
            <%= link_to "Accepted", accepted_sent_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
          <% if @rejected_sent_applications.present? %>
            <%= link_to "Rejected", rejected_sent_dash_path, class: "dashboard__menu-link dropdown-links-js", remote: true %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<% if @project_ids.any? %>
  <div class="dashboard__slider check-img-state-js">
    <div class="dashboard__chevron-wrapper"><h5 class="dashboard__chevron dashboard__chevron--left chevron--hidden past-chevron-left-js">&#x3c;</h5></div>
    <%= render "projects_dash" %>
    <div class="dashboard__chevron-wrapper"><h5 class="dashboard__chevron dashboard__chevron--right chevron--hidden past-chevron-right-js">&#x3e;</h5></div>
  </div>
<% elsif @collab_ids.any? %>
  <div class="dashboard__slider check-img-state-js">
    <div class="dashboard__chevron-wrapper dash-chevron"><h5 class="dashboard__chevron dashboard__chevron--left chevron--hidden past-chevron-left-js">&#x3c;</h5></div>
    <%= render "collabs_dash" %>
    <div class="dashboard__chevron-wrapper dash-chevron"><h5 class="dashboard__chevron dashboard__chevron--right chevron--hidden past-chevron-right-js">&#x3e;</h5></div>
  </div>
<% elsif @sent_inquiry_ids.any? %>
  <div class="dashboard__slider check-img-state-js">
    <div class="dashboard__chevron-wrapper dash-chevron"><h5 class="dashboard__chevron dashboard__chevron--left chevron--hidden past-chevron-left-js">&#x3c;</h5></div>
    <%= render "sent_dash" %>
    <div class="dashboard__chevron-wrapper dash-chevron"><h5 class="dashboard__chevron dashboard__chevron--right chevron--hidden past-chevron-right-js">&#x3e;</h5></div>
  </div>
<% else %>
  <div class="dashboard__no-activity-placeholder">
    <h5 class="dashboard__no-activity-text">No project nor collab in your portfolio yet...</h5>
    <i class="dashboard__no-activity-icon far fa-sad-cry"></i>
  </div>
<% end %>
<div class="dashboard__bottom-link-wrapper">
  <%= link_to user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, class: "dashboard__bottom-link" do %>
    <h3 class="dashboard__bottom-link-text">
      Delete your profile
      <div class="dashboard__bottom-link-underline"></div>
    </h3>
  <% end %>
</div>